# Generated by Django 4.2.7 on 2024-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contact_db',
            },
        ),
    ]
